-- 캘린더 개인 일정 — 공개 범위(2026-09-22)
--
-- 지금까지 couple_events 는 전부 "둘의 일정"이었다. 그런데 달력에 적고 싶은 것의 절반은
-- 회식·야근·병원처럼 <b>각자의 일정</b>이다. 그걸 넣을 자리가 없으니 캘린더가 기념일
-- 보관함처럼만 쓰였다.
--
-- 세 가지로 나눈다.
--   SHARED   우리 일정   — 지금까지의 모든 일정. 둘 다 보고, 둘 다 알림을 받는다.
--   PERSONAL 내 일정     — 상대도 <b>본다</b>(그게 달력을 같이 보는 이유다). 알림은 나만.
--   PRIVATE  나만 보기   — 상대에게 아예 보이지 않는다.
-- PERSONAL 과 PRIVATE 을 굳이 가른 이유: "내 일정"의 값어치는 상대가 내가 바쁜 날을
-- 아는 데 있고, 그걸 숨기고 싶은 날은 따로 있다(선물 준비 같은 것). 한 칸으로 합치면
-- 둘 중 하나는 못 쓴다.
--
-- <b>couple_id 는 그대로 NOT NULL 이다.</b> 개인 일정도 관계에 매달아 둔다 —
-- 이 앱의 모든 것이 relations 위에 올라가고(CLAUDE.md 7절), 그래야 RelationRecordPurger·
-- RelationRecordRestorer 의 기존 경로가 한 줄도 안 바뀐다. 대신 <b>혼자 쓰는 달력은 아직
-- 없다</b>(커플 미연결이면 캘린더 자체가 열리지 않는다) — 그건 별개의 기능이다.
--
-- 기존 행은 DEFAULT 로 전부 SHARED 가 된다 — 지금까지 등록된 일정은 실제로 둘의 일정이다.
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)
ALTER TABLE couple_events ADD COLUMN visibility VARCHAR(20) NOT NULL DEFAULT 'SHARED';
