-- 기능 크레딧 — 정액 구독 밖에서 파는 "N회 추가" (2026-09-25)
--
-- <b>왜</b>: 우리 이모지는 세트당 원가가 0 이 아니다(이미지 모델, 5장 ≈ 0.2 USD). 정액 구독
-- 안에서만 팔면 한도를 올릴수록 헤비 유저가 손실이 되고, 한도를 내리면 상품이 초라해진다.
-- 정액(구독)과 변동원가(세트)를 분리한다 — PRO 는 월 N세트를 포함하고, 그 이상은 세트 단위로
-- 산다. FREE 도 구독 없이 세트 하나를 살 수 있어 "체험 구매"가 된다(docs/BILLING_STATUS_2026-09-25.md §7).
--
-- 스티커 팩(V96)과 달리 <b>소모성</b>이다 — 사면 credits 가 늘고 쓰면 used 가 는다. 소유 여부가
-- 아니라 잔량을 묻는다. 어느 기능의 크레딧인지는 feature 컬럼(Feature enum 이름)이 말한다 —
-- 이모지 하나 때문에 만든 표지만 "회수 추가"가 필요한 다음 기능도 같은 표를 쓴다.
--
-- transaction_id UNIQUE: 검증 재호출(앱 재설치·연타)이 크레딧을 두 번 주지 않게 한다.
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)
CREATE TABLE feature_credits (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id),
    feature        VARCHAR(40)  NOT NULL,
    store          VARCHAR(20)  NOT NULL,             -- GOOGLE_PLAY | APP_STORE | MANUAL
    product_id     VARCHAR(100) NOT NULL,
    transaction_id VARCHAR(255) NOT NULL UNIQUE,
    credits        INT          NOT NULL,
    used           INT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 잔량 조회·차감이 매번 (user_id, feature) 로 들어온다
CREATE INDEX idx_feature_credits_user_feature ON feature_credits (user_id, feature);
