-- 커플 여행 (PLAN.md: Trip) — 여행 계획/기록 + 장소(places) 그룹핑
CREATE TABLE trips (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id       BIGINT       NOT NULL REFERENCES relations (id),
    title           VARCHAR(100) NOT NULL,
    start_date      DATE         NOT NULL,
    end_date        DATE         NOT NULL,   -- >= start_date (서비스 검증)
    memo            TEXT,
    cover_image_url VARCHAR(500),
    created_by      BIGINT       NOT NULL REFERENCES users (id),
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 장소를 여행으로 그룹핑 (여행 삭제 시 장소는 유지)
ALTER TABLE places ADD COLUMN trip_id BIGINT REFERENCES trips (id) ON DELETE SET NULL;

CREATE INDEX idx_trips_couple ON trips (couple_id, start_date DESC);
CREATE INDEX idx_places_trip ON places (trip_id);
