-- 나만의 하루 기록 — 상대에게 보이지 않는, 나에게 쓰는 오늘의 기록.
-- docs/PERSONAL_JOURNAL_DIRECTION_2026-10-02.md §3, docs/PERSONAL_JOURNAL_ANALYSIS_2026-10-02.md §1-1.
--
-- relation_id 가 없다 — 관계가 아니라 사람에게 저장해야 관계가 끝나도 남는다. 그래서 couple_id 로
-- 거르는 기존 조회(피드·내보내기 COUPLE 범위·지난 기록 삭제·복원) 어디에도 걸리지 않는다.
-- 삭제는 탈퇴(UserDataPurger)에서만.
--
-- 하루 1개 — (user_id, journal_date) 유니크가 월 보기 범위 조회 인덱스를 겸한다.
-- mood_emoji 는 mood_statuses 를 참조하지 않고 직접 저장한다: 그쪽은 couple_id NOT NULL 이라
-- 미연결이면 행이 없고, 지난 기록 삭제 때 지워진다(분석 §1-3).
-- 구조화 필드(체중·생리·수면 등)는 두지 않는다 — 원칙 6.
-- "우리 기록에 공유"(shared_post_id)는 1차-b 에서 별도 마이그레이션으로 붙인다.
CREATE TABLE journal_entries (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL REFERENCES users (id),
    journal_date DATE          NOT NULL,
    mood_emoji   VARCHAR(10),
    body         VARCHAR(2000),
    photo_url    VARCHAR(500),
    created_at   TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP,
    CONSTRAINT uk_journal_entries_user_date UNIQUE (user_id, journal_date)
);
