-- 식단 찌르기 — 상대가 오늘 식사를 안 남겼을 때 "뭐 먹었어?"를 한 번 보낸다.
-- docs/lovebody-direction_2026-10-02.md 2순위, LOVEBODY_REVIEW_2026-10-02.md §4(터치 말고 게임 찌르기 패턴).
--
-- 하루 한 번(KST) — (sender_id, nudge_date) 유니크가 그 규칙을 DB 에서 지킨다. 연타·동시 요청도 두 번째 INSERT 가
-- 막힌다. 채팅에 남지 않는 신호라 메시지 테이블을 쓰지 않는다. ON CONFLICT 같은 DB 전용 문법은 쓰지 않는다(CLAUDE.md 4절).
--
-- 삭제: 관계 단위는 RelationRecordPurger(relation_id), 탈퇴는 UserDataPurger(sender_id·receiver_id 양쪽).
--
-- 영향 행 수: 0 (새 테이블)
-- 롤백: drop table meal_nudges;
CREATE TABLE meal_nudges (
    id          BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT     NOT NULL REFERENCES relations (id),
    sender_id   BIGINT     NOT NULL REFERENCES users (id),
    receiver_id BIGINT     NOT NULL REFERENCES users (id),
    nudge_date  DATE       NOT NULL,
    created_at  TIMESTAMP  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP,
    CONSTRAINT uk_meal_nudges_sender_date UNIQUE (sender_id, nudge_date)
);
