-- V124 — 일상 댓글. 이모지 반응만으로는 "그 사진 어디야?" 같은 말을 나눌 자리가 없었다(P2).
--
-- 일상 포스트에만 단다(반응처럼 운동·식단 카드까지 넓히지 않는다 — 그쪽은 채팅에 공유하는 길이 있다).
-- 포스트가 지워지면 댓글도 함께 지워진다(ON DELETE CASCADE). 지난 기록 삭제·탈퇴는 그래도 명시적으로 거둔다
-- (RelationRecordPurger·UserDataPurger) — 삭제 순서를 코드에서 읽을 수 있게.
CREATE TABLE feed_comments (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT       NOT NULL REFERENCES feed_posts (id) ON DELETE CASCADE,
    author_id  BIGINT       NOT NULL REFERENCES users (id),
    content    VARCHAR(500) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 포스트의 댓글 목록(오래된 순)·카드의 댓글 수
CREATE INDEX idx_feed_comments_post ON feed_comments (post_id, created_at);
-- 탈퇴 때 내가 쓴 댓글 거두기
CREATE INDEX idx_feed_comments_author ON feed_comments (author_id);
