-- V125 — 하루 기록 리마인드(P2, 옵트인). 사용자가 고른 시각에, 그날 기록이 없을 때만 "한 줄 남겨 볼까요?"를 보낸다.
-- (H2 호환 구문만 — 테스트가 같은 마이그레이션을 적용한다)
--
-- 한 사람당 최대 한 행. 행이 없으면 꺼진 것이다(끄기 = 삭제) — meal_reminders(V78)와 같은 모양.
-- 알림 문구는 고정이다. 기록 내용은 어떤 경우에도 싣지 않는다(docs/PERSONAL_JOURNAL_ANALYSIS_2026-10-02.md §2-1).
CREATE TABLE journal_reminders (
    id            BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL REFERENCES users (id),
    reminder_time TIME      NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_journal_reminders_user UNIQUE (user_id)
);

-- 매분 도는 스케줄러가 "지금 이 분에 울려야 하는 행"을 훑는 조회
CREATE INDEX idx_journal_reminders_time ON journal_reminders (reminder_time);
