-- 식단 즐겨찾기 — 자주 먹는 음식을 이름·칼로리·매크로로 저장해 원탭 추가
CREATE TABLE favorite_foods (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    name       VARCHAR(100) NOT NULL,
    calories   INTEGER,
    carbs      INTEGER,
    protein    INTEGER,
    fat        INTEGER,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_favorite_foods_user ON favorite_foods (user_id, id DESC);
