-- 럽슐랭 장소의 "우리가 쌓는 메뉴" — 메뉴판을 찍어 AI 가 읽은 메뉴(이름·가격)와 그 메뉴판 사진.
-- 설계: docs/LOVELICHELIN_PLACE_MENU_2026-10-06.md
--
-- 카카오·네이버에는 메뉴 공개 API 가 없다. 그래서 둘이 직접 찍은 메뉴판으로 채운다.
-- place_menu_items: 한 장소의 메뉴 목록. 저장은 "통째로 바꾸기"(PUT) 라 sort_order 가 화면 순서다.
-- place_menu_photos: 메뉴판 사진. 메뉴를 다시 읽거나 가격을 눈으로 확인할 때 본다.
--
-- 사람 컬럼(updated_by·uploaded_by)에는 users FK 를 걸지 않는다 — 장소는 커플 것이라 관계 단위로만 지워지고
-- (RelationRecordPurger), 사람 단위 탈퇴 경로(UserDataPurger)가 이 표를 몰라도 되게.
-- places 가 지워지면 함께 지워진다(ON DELETE CASCADE). H2·PostgreSQL 공통 문법만(CLAUDE.md 4절).
-- 롤백: drop table place_menu_photos; drop table place_menu_items;
CREATE TABLE place_menu_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id   BIGINT       NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    name       VARCHAR(100) NOT NULL,
    price      INTEGER,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    updated_by BIGINT       NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_place_menu_items_place ON place_menu_items (place_id);

CREATE TABLE place_menu_photos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id    BIGINT       NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    image_url   VARCHAR(500) NOT NULL,
    uploaded_by BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_place_menu_photos_place ON place_menu_photos (place_id);
