-- 사용자 본인 운동 루틴 템플릿 (트레이너 배정 루틴과 별개) — 짐앱 스타일
CREATE TABLE workout_routines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    title      VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE workout_routine_exercises (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id    BIGINT       NOT NULL REFERENCES workout_routines (id) ON DELETE CASCADE,
    exercise_name VARCHAR(100) NOT NULL,
    category      VARCHAR(20),
    target_sets   INTEGER,
    reps          INTEGER,
    weight_kg     DECIMAL(6, 2),
    order_no      INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX idx_workout_routines_user ON workout_routines (user_id, id DESC);
CREATE INDEX idx_workout_routine_ex_routine ON workout_routine_exercises (routine_id);
