-- 신체 측정 & 진행 사진 — 체중·체지방·둘레 추적 + before/after 사진
CREATE TABLE body_metrics (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL REFERENCES users (id),
    measured_date DATE      NOT NULL DEFAULT CURRENT_DATE,
    weight_kg     DECIMAL(5, 2),
    body_fat_pct  DECIMAL(4, 1),
    waist_cm      DECIMAL(5, 1),
    photo_url     VARCHAR(500),
    memo          TEXT,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_body_metrics_user_date ON body_metrics (user_id, measured_date);
