-- 커플 챌린지/대결 — 기간 내 운동/식단 기록일로 겨루기 (점수는 원본에서 실시간 집계)
CREATE TABLE couple_challenges (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id  BIGINT       NOT NULL REFERENCES relations (id),
    type       VARCHAR(20)  NOT NULL,   -- WORKOUT | MEAL
    title      VARCHAR(100) NOT NULL,
    start_date DATE         NOT NULL,
    end_date   DATE         NOT NULL,
    stake      TEXT,                     -- 벌칙/보상 (선택)
    created_by BIGINT       NOT NULL REFERENCES users (id),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_couple_challenges_couple ON couple_challenges (couple_id, start_date DESC);
