-- 데일리 질문 (커플 Q&A) — 매일 질문에 둘 다 답하면 서로 공개
CREATE TABLE daily_answers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id     BIGINT       NOT NULL REFERENCES relations (id),
    question_date DATE         NOT NULL,
    user_id       BIGINT       NOT NULL REFERENCES users (id),
    question_text VARCHAR(200) NOT NULL,
    answer        TEXT         NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE (couple_id, question_date, user_id)
);

CREATE INDEX idx_daily_answers_couple_date ON daily_answers (couple_id, question_date DESC);
