-- 커플 여행 일자별 일정표 (PLAN.md: Trip Itinerary)
-- 여행(trips) 안에 Day별·시간순 일정 항목을 담는다. 장소(places) 연결은 선택
-- (place_id NULL 이면 "공항 도착" 같은 자유 항목).
CREATE TABLE trip_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT       NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    place_id   BIGINT       REFERENCES places (id) ON DELETE SET NULL,  -- 연결 장소(선택)
    day_no     INT          NOT NULL,           -- 1일차, 2일차 … (여행 기간 내, 서비스 검증)
    sort_order INT          NOT NULL,           -- 하루 안 순서 (0부터, 이동 시 재배치)
    start_time TIME,                            -- 시간대(선택)
    title      VARCHAR(100) NOT NULL,           -- 장소 없이도 자유 입력
    category   VARCHAR(30),                     -- 관광/식사/카페/이동/숙소 …
    memo       TEXT,
    created_by BIGINT       NOT NULL REFERENCES users (id),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trip_items_trip_day ON trip_items (trip_id, day_no, sort_order);
