-- 커플 여행 경비 정산 (PLAN.md: Trip Expenses)
-- 누가 얼마를 냈는지 기록하고, 커플 반반 기준으로 정산액을 계산한다.
CREATE TABLE trip_expenses (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT        NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    paid_by    BIGINT        NOT NULL REFERENCES users (id),   -- 낸 사람(커플 둘 중 하나)
    amount     NUMERIC(12,2) NOT NULL,
    currency   VARCHAR(3)    NOT NULL DEFAULT 'KRW',
    category   VARCHAR(30),                                    -- 식비/교통/숙박/쇼핑/기타
    day_no     INT,                                            -- 며칠차(선택)
    memo       VARCHAR(200),
    created_by BIGINT        NOT NULL REFERENCES users (id),
    created_at TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trip_expenses_trip ON trip_expenses (trip_id, created_at DESC);
