-- 커플 여행 준비물 체크리스트 (PLAN.md: Trip Checklist)
-- 커플이 함께 준비물을 적고 체크한다. 체크한 사람(checked_by)을 남겨 "누가 챙겼는지" 보인다.
CREATE TABLE trip_checklist_items (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT       NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    content    VARCHAR(200) NOT NULL,
    checked    BOOLEAN      NOT NULL DEFAULT FALSE,
    checked_by BIGINT       REFERENCES users (id),   -- 체크한 사람 (미체크면 NULL)
    sort_order INT          NOT NULL DEFAULT 0,
    created_by BIGINT       NOT NULL REFERENCES users (id),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trip_checklist_trip ON trip_checklist_items (trip_id, sort_order, id);
