-- 비밀번호 재설정 인증코드 (AUTH-07)
-- 코드 원문은 저장하지 않는다 — BCrypt 해시만 보관해 DB 유출 시에도 코드를 복원할 수 없게 한다.
CREATE TABLE password_reset_tokens (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    code_hash  VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    -- 검증 실패 누적 — 한도 초과 시 코드를 폐기해 6자리 무차별 대입을 막는다
    attempts   INT          NOT NULL DEFAULT 0,
    -- 사용 완료 시각. NULL 이면 미사용 (1회용 보장)
    used_at    TIMESTAMP,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 사용자별 유효 코드 조회 (재발급 시 기존 코드 무효화에도 사용)
CREATE INDEX idx_password_reset_user ON password_reset_tokens (user_id);
-- 만료분 정리 배치용
CREATE INDEX idx_password_reset_expires ON password_reset_tokens (expires_at);
