-- 커플 캘린더 — 기념일 외 일정(생일·데이트 약속 등) + D-day 푸시 대상
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)
CREATE TABLE couple_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id     BIGINT       NOT NULL REFERENCES relations (id),
    title         VARCHAR(100) NOT NULL,
    event_date    DATE         NOT NULL,
    event_type    VARCHAR(20)  NOT NULL DEFAULT 'ETC',   -- ANNIVERSARY | BIRTHDAY | DATE | ETC
    repeat_yearly BOOLEAN      NOT NULL DEFAULT FALSE,   -- 생일·기념일 등 매년 반복
    memo          VARCHAR(500),
    created_by    BIGINT       NOT NULL REFERENCES users (id),
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_couple_events_couple_date ON couple_events (couple_id, event_date);
