-- 채팅 개선 — 메시지 리액션 / 답장(인용) / 수정·삭제
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)

-- 메시지 이모지 리액션 (feed_reactions 와 같은 구조: 재요청 시 토글)
CREATE TABLE chat_message_reactions (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT      NOT NULL REFERENCES chat_messages (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    emoji      VARCHAR(10) NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    UNIQUE (message_id, user_id, emoji)
);
CREATE INDEX idx_chat_message_reactions_message ON chat_message_reactions (message_id);

-- 답장(인용) — 원본 메시지가 지워져도 답장은 남기고 참조만 끊는다
ALTER TABLE chat_messages ADD COLUMN reply_to_id BIGINT REFERENCES chat_messages (id) ON DELETE SET NULL;

-- 수정/삭제 — 삭제는 행을 지우지 않고 표시만 남긴다(답장·리액션의 참조 무결성 유지)
ALTER TABLE chat_messages ADD COLUMN edited_at  TIMESTAMP;
ALTER TABLE chat_messages ADD COLUMN deleted_at TIMESTAMP;
