-- 운동 기능 확장 0단계 — 공통 데이터 기반
-- 1) 종목 카탈로그: 자극 부위(muscle_group)/기구(equipment) 태그의 출처.
--    대체 종목 추천(②), 자극 부위 시각화(BurnFit 벤치마킹), AI 추천 고도화(Fitbod 벤치마킹)가
--    전부 이 태그에 의존하므로 가장 먼저 세운다.
CREATE TABLE exercise_catalog (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL UNIQUE,
    category     VARCHAR(20)  NOT NULL,                    -- 근력 / 유산소 / 유연성
    muscle_group VARCHAR(20)  NOT NULL,                     -- 가슴/등/어깨/하체/팔/코어/전신 등
    equipment    VARCHAR(30),                               -- 바벨/덤벨/머신/케이블/맨몸 등
    created_by   BIGINT REFERENCES users (id),               -- NULL = 시스템 기본 제공, 값 있으면 사용자 커스텀 종목
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_exercise_catalog_muscle_group ON exercise_catalog (muscle_group);

INSERT INTO exercise_catalog (name, category, muscle_group, equipment) VALUES
    ('벤치프레스', '근력', '가슴', '바벨'),
    ('덤벨 프레스', '근력', '가슴', '덤벨'),
    ('인클라인 벤치프레스', '근력', '가슴', '바벨'),
    ('푸시업', '근력', '가슴', '맨몸'),
    ('케이블 크로스오버', '근력', '가슴', '케이블'),
    ('딥스', '근력', '가슴', '맨몸'),
    ('데드리프트', '근력', '등', '바벨'),
    ('바벨 로우', '근력', '등', '바벨'),
    ('랫풀다운', '근력', '등', '머신'),
    ('풀업', '근력', '등', '맨몸'),
    ('시티드 케이블 로우', '근력', '등', '케이블'),
    ('오버헤드 프레스', '근력', '어깨', '바벨'),
    ('덤벨 숄더프레스', '근력', '어깨', '덤벨'),
    ('사이드 레터럴 레이즈', '근력', '어깨', '덤벨'),
    ('페이스 풀', '근력', '어깨', '케이블'),
    ('스쿼트', '근력', '하체', '바벨'),
    ('레그프레스', '근력', '하체', '머신'),
    ('런지', '근력', '하체', '덤벨'),
    ('레그컬', '근력', '하체', '머신'),
    ('레그익스텐션', '근력', '하체', '머신'),
    ('힙쓰러스트', '근력', '하체', '바벨'),
    ('바벨 컬', '근력', '팔', '바벨'),
    ('덤벨 컬', '근력', '팔', '덤벨'),
    ('해머 컬', '근력', '팔', '덤벨'),
    ('트라이셉스 익스텐션', '근력', '팔', '케이블'),
    ('플랭크', '근력', '코어', '맨몸'),
    ('크런치', '근력', '코어', '맨몸'),
    ('행잉 레그레이즈', '근력', '코어', '맨몸'),
    ('케이블 크런치', '근력', '코어', '케이블'),
    ('러닝', '유산소', '전신', '맨몸'),
    ('사이클', '유산소', '전신', '머신'),
    ('로잉머신', '유산소', '전신', '머신'),
    ('폼롤러 스트레칭', '유연성', '전신', '맨몸'),
    ('요가 스트레칭', '유연성', '전신', '맨몸');

-- 2) 루틴 종목/운동 세트에 카탈로그 참조 + 태그 비정규화 컬럼 추가
--    (자유 텍스트 종목명 입력 흐름은 유지하되, 태그가 있으면 대체 종목·시각화에 활용)
ALTER TABLE workout_routine_exercises ADD COLUMN exercise_catalog_id BIGINT REFERENCES exercise_catalog (id);
ALTER TABLE workout_routine_exercises ADD COLUMN muscle_group VARCHAR(20);
ALTER TABLE workout_routine_exercises ADD COLUMN equipment VARCHAR(30);

ALTER TABLE workout_sets ADD COLUMN exercise_catalog_id BIGINT REFERENCES exercise_catalog (id);
ALTER TABLE workout_sets ADD COLUMN muscle_group VARCHAR(20);
ALTER TABLE workout_sets ADD COLUMN equipment VARCHAR(30);

-- 3) 운동 기록이 어느 루틴에서 시작됐는지 연결 — 스마트 루틴 동기화(①)의 전제.
--    루틴이 삭제돼도 과거 기록은 남아야 하므로 SET NULL.
ALTER TABLE workouts
    ADD COLUMN source_routine_id BIGINT REFERENCES workout_routines (id) ON DELETE SET NULL;
CREATE INDEX idx_workouts_source_routine ON workouts (source_routine_id);

-- 4) 세트별 실제 수행 기록(무게/횟수/완료 여부) — 지금까지 workout_sets 한 행이
--    "종목당 N세트 x 무게 x 횟수" 하나의 평균값만 담고 있어, 세트마다 다른 무게/횟수를
--    남기거나(예: 1세트 60kg x10, 2세트 55kg x8) 직전 세트 값을 세트 단위로 프리필(④)할 수 없었다.
CREATE TABLE workout_set_entries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_set_id BIGINT  NOT NULL REFERENCES workout_sets (id) ON DELETE CASCADE,
    set_no         INT     NOT NULL,
    weight_kg      DECIMAL(6, 2),
    reps           INT,
    completed      BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_workout_set_entries_set ON workout_set_entries (workout_set_id);
