-- 관계 모델 N인 확장 1단계 — relation_members 조인 테이블 (README "관계 모델" 참고)
-- 커플/트레이너는 기존 user_a_id/user_b_id 를 유지한 채 멤버 행을 함께 기록하고(이중 기록),
-- 신규 FAMILY(N인) 관계는 relation_members 를 멤버십의 원천으로 사용한다.

CREATE TABLE relation_members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT      NOT NULL REFERENCES relations (id),
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    member_role VARCHAR(20) NOT NULL,               -- PARTNER / TRAINER / MEMBER / GUARDIAN / CHILD
    joined_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_relation_members UNIQUE (relation_id, user_id)
);
CREATE INDEX idx_relation_members_user ON relation_members (user_id);

-- FAMILY 표시 이름 (커플/트레이너는 NULL)
ALTER TABLE relations ADD COLUMN relation_name VARCHAR(50);

-- backfill: 기존 관계의 A/B 슬롯을 멤버 행으로 옮긴다.
-- COUPLE 은 양쪽 다 PARTNER, TRAINER_MEMBER 는 A=TRAINER / B=MEMBER.
INSERT INTO relation_members (relation_id, user_id, member_role, joined_at)
SELECT r.id,
       r.user_a_id,
       CASE WHEN r.relation_type = 'TRAINER_MEMBER' THEN 'TRAINER' ELSE 'PARTNER' END,
       COALESCE(r.connected_at, r.created_at)
FROM relations r;

INSERT INTO relation_members (relation_id, user_id, member_role, joined_at)
SELECT r.id,
       r.user_b_id,
       CASE WHEN r.relation_type = 'TRAINER_MEMBER' THEN 'MEMBER' ELSE 'PARTNER' END,
       COALESCE(r.connected_at, r.created_at)
FROM relations r
WHERE r.user_b_id IS NOT NULL;
