-- 즐겨찾기를 "세트"로 확장 — 여러 음식을 한 번에 등록해 원탭으로 재사용
-- (예: 닭가슴살 100g + 고구마 150g + 아몬드). 항목별 이름·칼로리·매크로를 따로 들고,
-- 세트 전체 칼로리/매크로는 항목 합산으로 계산한다(favorite_foods 에는 더 이상 저장하지 않는다).
CREATE TABLE favorite_food_items (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    favorite_food_id BIGINT       NOT NULL REFERENCES favorite_foods (id) ON DELETE CASCADE,
    name             VARCHAR(100) NOT NULL,
    calories         INTEGER,
    carbs            INTEGER,
    protein          INTEGER,
    fat              INTEGER,
    order_no         INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX idx_favorite_food_items_favorite ON favorite_food_items (favorite_food_id, order_no);

-- 기존 단일 음식 즐겨찾기를 세트의 첫(유일한) 항목으로 이전 — 데이터 손실 없이 새 구조로 옮긴다.
-- favorite_foods.calories/carbs/protein/fat 컬럼은 더 이상 매핑되지 않지만, 파괴적 변경을 피하려
-- 그대로 둔다(신규 코드는 favorite_food_items 합산만 본다).
INSERT INTO favorite_food_items (favorite_food_id, name, calories, carbs, protein, fat, order_no)
SELECT id, name, calories, carbs, protein, fat, 0 FROM favorite_foods;
