-- ③ 종목별 휴식 시간 사전 설정 — 세션 전역 타이머(60/90/120s) 대신 종목마다 다른 값을 쓸 수 있게.
ALTER TABLE workout_routine_exercises ADD COLUMN rest_seconds INTEGER;

-- ④ 대체 종목 사전 지정 — 루틴 작성 시 종목마다 1~2개 대체 후보를 미리 묶어둔다.
-- 세션 중 '대체 종목으로 교체'를 누르면 자극 부위 전체 탐색보다 이 목록이 먼저 뜬다.
CREATE TABLE workout_routine_exercise_alternatives (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_exercise_id BIGINT  NOT NULL REFERENCES workout_routine_exercises (id) ON DELETE CASCADE,
    exercise_catalog_id BIGINT  NOT NULL REFERENCES exercise_catalog (id),
    sort_order          INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_routine_ex_alt_routine_ex ON workout_routine_exercise_alternatives (routine_exercise_id);
