-- 구독(PRO 플랜) — 결제 연동 전에 "판정 경로"만 먼저 깔아둔다.
--
-- 무료 체험 기간에는 fitto.plan.free-trial=true 로 전원 PRO 로 판정되므로 이 테이블은
-- 비어 있다. 결제를 붙이는 시점에 스토어 웹훅이 여기에 행을 넣고, 플래그만 끄면 된다.
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)
CREATE TABLE subscriptions (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id),
    plan           VARCHAR(20)  NOT NULL DEFAULT 'PRO',
    status         VARCHAR(20)  NOT NULL,             -- ACTIVE | EXPIRED | REFUNDED
    store          VARCHAR(20)  NOT NULL,             -- GOOGLE_PLAY | APP_STORE | MANUAL
    product_id     VARCHAR(100) NOT NULL,
    -- 스토어 거래 식별자. 웹훅(RTDN / App Store Notifications)은 같은 이벤트를 여러 번
    -- 보내므로, UNIQUE 로 막아 재전송이 행을 늘리지 못하게 한다.
    purchase_token VARCHAR(255) NOT NULL UNIQUE,
    started_at     TIMESTAMP    NOT NULL,
    -- NULL = 만료 없음. 얼리 커플 "평생 PRO" 수동 부여(store = MANUAL)에 쓴다.
    expires_at     TIMESTAMP,
    auto_renew     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_subscriptions_user_status ON subscriptions (user_id, status);
