-- 식단 추가 영양소(당류·나트륨·식이섬유) — target 은 두지 않는 정보성 지표라 meals 에만 컬럼 추가
ALTER TABLE meals ADD COLUMN sugar INT;
ALTER TABLE meals ADD COLUMN sodium INT;   -- mg 단위 (다른 컬럼은 g)
ALTER TABLE meals ADD COLUMN fiber INT;

-- 하루 물 섭취 목표(ml) — 미설정 시 서비스 기본값(2000ml)
ALTER TABLE nutrition_goals ADD COLUMN target_water_ml INT;

-- 물 섭취 기록 — 날짜별 누적치 1행. 화면의 "+250ml" 버튼이 이 행을 증분 upsert 한다.
CREATE TABLE water_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    log_date   DATE        NOT NULL,
    amount_ml  INT         NOT NULL DEFAULT 0,
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, log_date)
);
