-- 간헐적 단식 세션 — ended_at 이 NULL 이면 진행 중. 사용자당 진행 중 세션은 서비스 레이어에서
-- 1개로 제한한다(H2 호환을 위해 부분 유니크 인덱스는 쓰지 않는다).
CREATE TABLE fasting_sessions (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES users (id),
    plan_type    VARCHAR(20) NOT NULL,
    target_hours INT         NOT NULL,
    started_at   TIMESTAMP   NOT NULL,
    ended_at     TIMESTAMP,
    created_at   TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_fasting_sessions_user_active ON fasting_sessions (user_id, ended_at);
