-- 식단 기록을 "음식 항목" 단위로 확장 — 반찬 하나(공기밥·김치)만 고치거나 빼도
-- 끼니 전체 칼로리가 알아서 다시 계산되게 한다. AI 분석(FoodAnalysisService)이 이미
-- 음식별 칼로리·매크로를 내주는데 지금까지는 합계만 남기고 버려왔다.
--
-- 즐겨찾기(favorite_foods ← favorite_food_items, V35)와 같은 세트/항목 구조다.
CREATE TABLE meal_items (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id  BIGINT       NOT NULL REFERENCES meals (id) ON DELETE CASCADE,
    name     VARCHAR(100) NOT NULL,
    portion  VARCHAR(50),               -- "1인분", "밥 반 공기" — AI 추정 양
    calories INTEGER,
    carbs    INTEGER,
    protein  INTEGER,
    fat      INTEGER,
    order_no INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX idx_meal_items_meal ON meal_items (meal_id, order_no);

-- meals.calories/carbs/protein/fat 은 그대로 둔다. 항목 합계 캐시 역할이다.
-- 스트릭·피드·주간 리캡·영양 대시보드·AI 코칭이 전부 이 컬럼을 조인 없이 집계로 읽고 있어서,
-- 정규화한다고 지우면 그 전부를 같이 고쳐야 한다. 항목이 바뀌면 서버가 다시 합산해 채운다.
--
-- 기존 기록은 백필하지 않는다 — memo 는 자유 서술("닭가슴살 샐러드, 오늘 좀 짰음")이라
-- 그대로 항목 이름으로 옮기면 음식이 아닌 문장에 끼니 전체 칼로리가 붙는다. 항목이 없는
-- 기록은 지금처럼 memo 로 보여주고(레거시 경로), 수정 화면에서 항목을 직접 채울 수 있다.
