-- 루틴에 요일 배정 — 짐워크(GymWork) 스타일로 "Day1은 월/목, Day2는 화/금" 처럼
-- 반복되는 요일에 미리 루틴을 매어둔다. 기존 루틴은 전부 요일이 비어 있으므로
-- 지금처럼 특정 요일에 매이지 않는 자유 루틴으로 그대로 동작한다 — 새 테이블
-- 추가만으로 기존 동작에 영향 없음.
CREATE TABLE workout_routine_days (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id  BIGINT      NOT NULL REFERENCES workout_routines (id) ON DELETE CASCADE,
    day_of_week VARCHAR(10) NOT NULL   -- MONDAY/TUESDAY/... (java.time.DayOfWeek 이름 그대로)
);
CREATE UNIQUE INDEX idx_workout_routine_days_unique ON workout_routine_days (routine_id, day_of_week);
CREATE INDEX idx_workout_routine_days_day ON workout_routine_days (day_of_week);
