-- 종목 하나의 목표를 세트 단위로 나눈다. 지금까지는 종목당 목표 세트수·횟수·무게가
-- 한 벌뿐이라 램프업/피라미드/드롭세트/탑세트+백오프처럼 세트마다 다른 값을 계획에
-- 담을 수 없었다 — "탑세트+백오프" 프리셋이 실제로는 그냥 4x8 을 넣고 힌트 문구만
-- 띄우던 이유가 이것이다(WorkoutRoutineFormScreen SET_PRESETS).
--
-- 기록(workout_set_entries, V28)은 이미 세트 단위인데 계획만 뭉뚱그려져 있었다 — 짝을 맞춘다.
CREATE TABLE routine_exercise_sets (
    id                   BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_exercise_id  BIGINT  NOT NULL REFERENCES workout_routine_exercises (id) ON DELETE CASCADE,
    set_no               INTEGER NOT NULL,
    reps                 INTEGER,
    weight_kg            NUMERIC(6, 2),
    -- 세트 성격 — WARMUP/NORMAL/TOP/BACKOFF/DROP. UI 배지 표시용, 합계 계산에는 안 쓴다.
    set_type             VARCHAR(10)
);
CREATE INDEX idx_routine_exercise_sets_exercise ON routine_exercise_sets (routine_exercise_id, set_no);

-- workout_routine_exercises 의 target_sets/reps/weight_kg 는 그대로 둔다. 루틴 목록 카드·
-- 세션 프리필·AI 추천이 전부 이 요약 컬럼을 조인 없이 읽으므로, 세트가 있으면 서버가
-- 다시 계산해 채운다(식단 항목 합계 컬럼과 같은 전략). 기존 루틴은 세트가 비어 있으므로
-- 세션 시작 시 지금처럼 목표 세트수만큼 같은 값으로 균등 분배된다 — 동작 변화 없음.
