-- 커플 음성 응원 — 애인이 녹음한 짧은 응원 문구를 운동 중 정해진 순간(휴식 종료·PR·
-- 운동 완료)에 재생한다. 짐워크·플랜핏에도 없는, 커플 앱만의 기능.
--
-- 문구는 고정 3종(REST_END/PR/WORKOUT_COMPLETE)이라 사용자당 최대 3행뿐이다.
-- 사진(피드·앨범·식단 등)처럼 계속 쌓이는 자원이 아니라 재녹음은 교체이지 누적이
-- 아니므로, 사진과 달리 업로드 한도(PlanGuard)를 걸지 않는다.
CREATE TABLE voice_clips (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    phrase     VARCHAR(20)  NOT NULL,   -- REST_END / PR / WORKOUT_COMPLETE
    audio_url  TEXT         NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX idx_voice_clips_user_phrase ON voice_clips (user_id, phrase);
