-- 무드 상태 — Obimy 벤치마킹(PLAN.md "무드 상태" 참고). daily_answers 와 같은 모양(관계별 로그).
-- "지금 상태"는 최신 행으로 조회한다. UNIQUE 를 두지 않는다 — 하루에 여러 번 바뀔 수 있어야 한다.
CREATE TABLE mood_statuses (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id  BIGINT       NOT NULL REFERENCES relations (id),
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    emoji      VARCHAR(10)  NOT NULL,
    message    VARCHAR(20),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_mood_statuses_couple_user ON mood_statuses (couple_id, user_id, created_at DESC);
