-- 커플 캐릭터 — 설계서 미정, character-growth-logging-feature.
--
-- 커플(relation) 단위로 1마리. 운동/식단 기록 시 성장치(growth_point)가 오르고,
-- 둘 다 같은 날 기록하면 보너스가 더 붙는다. 장기 미기록 시 배치(CharacterDecayJob,
-- 별도 예정)가 growth_point 를 깎을 수 있다 — 정책(유예일수/감소폭/on-off)은
-- fitto.character.decay-enabled 등 애플리케이션 설정에서 조정한다(스키마 변경 불필요).
--
-- 성장 단계(알/새싹/... 등)는 LevelResponse 와 마찬가지로 growth_point 에서 매번 파생
-- 계산한다 — 퇴화로 growth_point 가 줄어들 수 있어서 단계를 별도 컬럼으로 저장하면
-- 드리프트가 생긴다.
CREATE TABLE couple_characters (
    id                          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id                 BIGINT      NOT NULL UNIQUE REFERENCES relations (id),

    -- 현재 성장치. 퇴화로 줄어들 수 있어 "누적합"이 아니라 "현재 값" — 0 하한.
    growth_point                INT         NOT NULL DEFAULT 0,

    -- 운동 기록으로 성장치가 반영된 마지막 날짜(dedup) + 그날 "둘 다 기록" 보너스 지급 여부.
    -- 하루에 여러 번 운동을 기록해도 이 날짜와 같으면 무시하고, 상대가 나중에 기록을
    -- 완성하면(bonus_granted=false 인 채로 날짜만 같음) 보너스만 추가로 얹는다.
    last_workout_growth_date    DATE,
    workout_both_bonus_granted  BOOLEAN     NOT NULL DEFAULT FALSE,

    -- 식단 기록 쪽도 동일한 구조.
    last_meal_growth_date       DATE,
    meal_both_bonus_granted     BOOLEAN     NOT NULL DEFAULT FALSE,

    -- 퇴화 배치가 마지막으로 이 행을 처리한 날짜 — 같은 날 중복 실행되어도 두 번 깎지
    -- 않도록 막는 idempotency 가드.
    last_decayed_date           DATE,

    created_at                  TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_couple_characters_relation ON couple_characters (relation_id);
