-- 커플 루틴 선물하기 — 내 운동 루틴을 애인에게 보내면, 전송 시점에 뜬 스냅샷(무게는 비운 채
-- 종목 구성만)을 애인이 수락할 때 애인 소유 루틴으로 복사한다. 스냅샷을 별도로 두는 이유는
-- 보낸 사람이 원본을 그 사이 고치거나 지워도 선물 내용이 바뀌지 않게 하기 위함이다.
CREATE TABLE routine_gifts (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id           BIGINT       NOT NULL REFERENCES relations (id),
    sender_id             BIGINT       NOT NULL REFERENCES users (id),
    receiver_id           BIGINT       NOT NULL REFERENCES users (id),
    snapshot_routine_id   BIGINT       NOT NULL REFERENCES workout_routines (id),
    -- 수락 시 receiver 소유로 새로 만들어진 루틴 — 수락 전엔 NULL
    resulting_routine_id  BIGINT REFERENCES workout_routines (id),
    message               VARCHAR(200),
    status                VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at            TIMESTAMP    NOT NULL DEFAULT NOW(),
    responded_at          TIMESTAMP
);

CREATE INDEX idx_routine_gifts_receiver ON routine_gifts (receiver_id, status, id DESC);
CREATE INDEX idx_routine_gifts_sender ON routine_gifts (sender_id, id DESC);
