-- 즐겨찾기 음식 공유 — 자주 먹는 음식 세트를 애인에게 보내면, 전송 시점 스냅샷(항목 그대로)을
-- 애인이 수락할 때 애인 소유 즐겨찾기로 복사한다. 운동 루틴 선물(routine_gifts, V49)과 같은
-- 방침이지만, 즐겨찾기는 시스템 템플릿 같은 "주인 없는 행" 개념이 없어(favorite_foods.user_id
-- 는 항상 NOT NULL) 스냅샷 항목을 이 도메인 전용 테이블에 직접 담는다 — favorite_foods 는
-- 건드리지 않는다.
CREATE TABLE favorite_food_gifts (
    id                         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id                BIGINT       NOT NULL REFERENCES relations (id),
    sender_id                  BIGINT       NOT NULL REFERENCES users (id),
    receiver_id                BIGINT       NOT NULL REFERENCES users (id),
    -- 전송 시점 세트 라벨 스냅샷 — 이후 원본 이름이 바뀌어도 영향받지 않는다
    name                       VARCHAR(100) NOT NULL,
    message                    VARCHAR(200),
    status                     VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    -- 수락 시 receiver 소유로 새로 만들어진 즐겨찾기 — 수락 전엔 NULL
    resulting_favorite_food_id BIGINT REFERENCES favorite_foods (id),
    created_at                 TIMESTAMP    NOT NULL DEFAULT NOW(),
    responded_at               TIMESTAMP
);

CREATE INDEX idx_favorite_food_gifts_receiver ON favorite_food_gifts (receiver_id, status, id DESC);
CREATE INDEX idx_favorite_food_gifts_sender ON favorite_food_gifts (sender_id, id DESC);

-- 스냅샷 항목 — favorite_food_items 구조를 그대로 미러링하되 소유는 gift 다.
CREATE TABLE favorite_food_gift_items (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gift_id  BIGINT       NOT NULL REFERENCES favorite_food_gifts (id) ON DELETE CASCADE,
    name     VARCHAR(100) NOT NULL,
    calories INTEGER,
    carbs    INTEGER,
    protein  INTEGER,
    fat      INTEGER,
    order_no INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX idx_favorite_food_gift_items_gift ON favorite_food_gift_items (gift_id, order_no);
