-- 맞춤 프로그램(짐워크 스타일, 주차 지정) — 요일별 Day 루틴들을 하나의 프로그램으로 묶는다.
-- 지금까지는 "프로그램명 - Day1/Day2/..." 처럼 제목 문자열에만 묶음이 남고, 저장이 끝나면
-- 완전히 독립된 루틴 N개로 흩어져 "내 루틴" 목록에 전부 평면 나열되던 문제를 해소한다.
CREATE TABLE workout_programs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id),
    title        VARCHAR(80)  NOT NULL,
    -- 몇 주짜리 프로그램인지 — 진행률 표시("3주차 / 8주차")용. Day 루틴 자체는 매주 그대로
    -- 반복되고(주차별로 내용이 달라지진 않는다), 이 값은 기간 표시·진행률 계산에만 쓰인다.
    total_weeks  INT          NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

ALTER TABLE workout_routines ADD COLUMN program_id BIGINT REFERENCES workout_programs (id);
-- 프로그램 소속일 때만 1부터 시작하는 순번(Day1=1, Day2=2…). 자유 루틴은 NULL.
ALTER TABLE workout_routines ADD COLUMN day_no INT;
CREATE INDEX idx_workout_routines_program ON workout_routines (program_id, day_no);
