-- 럽슐랭 등급 시스템: 장소당 "나의 대표 평점" 1개 + "상대의 대표 평점" 1개를 별도
-- 테이블로 분리 저장한다. 기존 place_visits.rating(방문기록별 별점, blended 평균)과는
-- 별개 개념이다 — 방문할 때마다 남기는 기록이 아니라, 장소당 한 사람당 딱 1개만 유지되는
-- "대표 평점"이며 재평가하면 upsert 된다. places 에는 산정된 등급(tier)과 인증 시각을
-- 캐싱해 목록 조회마다 다시 계산하지 않게 한다.
CREATE TABLE place_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    revisit_intent BOOLEAN,
    rated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (place_id, user_id)
);
CREATE INDEX idx_place_ratings_place ON place_ratings (place_id);

-- 0=후보/일반, 1~3=럽스타 등급. 둘 다 평가하고 둘 다 3점 이상이어야 1 이상이 된다
-- (산정 로직은 PlaceService.computeTier 참고).
ALTER TABLE places ADD COLUMN lovelichelin_tier INTEGER NOT NULL DEFAULT 0;
ALTER TABLE places ADD COLUMN lovelichelin_certified_at TIMESTAMP;
