-- 통화 세션 — PLAN.md "통화·영상통화" 1단계. 미디어(오디오/비디오)는 Stream Video 가
-- 전담하고, 이 테이블은 "누가 누구에게 걸었는지"(발신·수락·거절·종료·부재중)만 기록한다.
-- status 로 생명주기를 구분한다: RINGING → ONGOING → ENDED, 또는 RINGING → MISSED/DECLINED.
-- 24시간 넘게 RINGING/ONGOING 이면 스케줄러(CallSessionSweeper)가 강제 종료한다.
CREATE TABLE call_sessions (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id        BIGINT       NOT NULL REFERENCES relations (id),
    caller_id        BIGINT       NOT NULL REFERENCES users (id),
    callee_id        BIGINT       NOT NULL REFERENCES users (id),
    call_type        VARCHAR(10)  NOT NULL,                    -- VOICE / VIDEO
    status           VARCHAR(12)  NOT NULL DEFAULT 'RINGING',  -- RINGING/ONGOING/ENDED/MISSED/DECLINED
    provider_call_id VARCHAR(100) NOT NULL,                    -- Stream call id
    started_at       TIMESTAMP,                                -- 수락 시각(=통화 시작)
    ended_at         TIMESTAMP,
    duration_sec     INT,
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_call_sessions_couple ON call_sessions (couple_id, created_at DESC);
