-- 최소 이벤트 로깅 — 2026-08 진단 리포트가 "예정"으로 남겨둔 항목. Sentry 는 에러만 수집해서
-- 지금까지 기능 효과를 측정할 방법이 전무했다(README "효과를 측정할 방법이 없습니다" 참고).
--
-- user_id/relation_id 는 의도적으로 FK 를 걸지 않는다 — 이 저장소의 다른 모든 테이블은
-- users/relations 를 참조하면 UserDataPurger/RelationRecordPurger 를 함께 갱신해야 하고,
-- 하나라도 빠지면 탈퇴가 FK 위반으로 실패한다(이번에도 실제로 두 번 겪은 사고). 이벤트 로그는
-- ① 탈퇴해도 지울 개인정보가 없는 익명 집계용 숫자 로그이고(사용자 행이 사라지면 그 id 로는
-- 아무것도 다시 조회할 수 없다), ② 탈퇴 후에도 "이 기능이 얼마나 쓰였는지" 집계 가치가 남아야
-- 하므로, 애초에 삭제 대상이 아니다 — purger 목록에 넣지 않아도 되게 설계한다.
CREATE TABLE event_logs (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    relation_id BIGINT,
    -- SIGNUP / LOGIN / COUPLE_CONNECTED / HOME_VIEWED / FEATURE_USED / FEATURE_BLOCKED 등
    -- (com.fitto.common.analytics.AnalyticsEvent 상수 참고)
    event_type  VARCHAR(40) NOT NULL,
    -- FEATURE_USED/FEATURE_BLOCKED 에서 어떤 Feature 인지 등 — 자유 문자열 하나만, JSON 아님
    detail      VARCHAR(50),
    created_at  TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- 집계 쿼리(기간별 · 이벤트별 · 사용자별) 가 전부 이 세 축을 탄다.
CREATE INDEX idx_event_logs_type_created ON event_logs (event_type, created_at);
CREATE INDEX idx_event_logs_user_type ON event_logs (user_id, event_type, created_at);
