-- 커플 응원 리액션 — 2026-08 진단 리포트 "커플 응원 리액션".
--
-- 지금까지 이모지 반응은 직접 쓴 일상 포스트에만 달렸다. 정작 매일 쌓이는 건 운동·식단·
-- 맛집 방문 카드인데, 거기엔 상대가 반응할 방법이 없어서 "기록을 상대가 봐주고 응원해주는
-- 순간"이라는 앱의 존재 이유가 절반만 동작하고 있었다.
--
-- post_id(단일 FK) 를 (target_type, target_id) 로 넓힌다. 컬럼 이름·유니크·외래키가 한꺼번에
-- 바뀌므로 ALTER 를 쌓는 대신 새 테이블로 옮겨 담는다. ALTER 로 하려면 V9 에서 이름 없이
-- 만든 제약(UNIQUE·FK)의 이름을 알아야 하는데, 그 이름은 Postgres(운영)와 H2(테스트)가
-- 서로 다르게 붙여서 한쪽에서만 깨지는 마이그레이션이 된다.
--
-- FK 가 사라지는 대가: feed_posts 의 ON DELETE CASCADE 를 잃는다. 그래서 반응을 지우는
-- 책임이 코드로 넘어온다 — FeedService.deletePost / WorkoutService.delete / MealService.delete
-- / PlaceService.deleteVisit 과 두 purger(UserDataPurger·RelationRecordPurger) 가 함께 지운다.
-- user_id FK 는 그대로 두었다: 이게 있어야 purger 누락이 탈퇴 실패로 즉시 드러난다
-- (README 가 경고한, 이 저장소에서 이미 두 번 겪은 사고 패턴).
CREATE TABLE feed_reactions_v2 (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- POST / WORKOUT / MEAL / PLACE_VISIT (com.fitto.feed.dto.FeedItemType)
    target_type VARCHAR(20) NOT NULL,
    target_id   BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    emoji       VARCHAR(10) NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_feed_reactions_target UNIQUE (target_type, target_id, user_id, emoji)
);

INSERT INTO feed_reactions_v2 (target_type, target_id, user_id, emoji, created_at)
SELECT 'POST', post_id, user_id, emoji, created_at FROM feed_reactions;

DROP TABLE feed_reactions;
ALTER TABLE feed_reactions_v2 RENAME TO feed_reactions;

CREATE INDEX idx_feed_reactions_target ON feed_reactions (target_type, target_id);
-- 탈퇴 시 "내가 남긴 반응" 을 지우는 경로(UserDataPurger) 가 이 축을 탄다.
CREATE INDEX idx_feed_reactions_user ON feed_reactions (user_id);
