-- 운동 부스터 ("음성 응원 2.0") — 2026-08 진단 리포트 "운동 부스터".
--
-- 기존 voice_clips 는 문구별 상설 클립(사용자당 문구마다 1개, 재녹음은 교체)이다.
-- 부스터는 성격이 반대다: 애인이 지금 이 순간을 위해 녹음해 보내고, 상대의 <b>다음
-- 세션 시작 때 한 번 재생되고 소멸</b>한다. 일회성이라 같은 테이블에 담을 수 없다
-- (voice_clips 는 교체 모델이라 "쌓였다가 하나씩 소비"가 표현되지 않는다).
--
-- played_at 이 소비 표시를 겸한다 — 별도 상태 컬럼을 두면 "재생됐는데 PENDING" 같은
-- 어긋난 조합이 생길 수 있다.
CREATE TABLE workout_boosters (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT    NOT NULL REFERENCES relations (id),
    sender_id   BIGINT    NOT NULL REFERENCES users (id),
    receiver_id BIGINT    NOT NULL REFERENCES users (id),
    audio_url   TEXT      NOT NULL,
    -- 한 줄 메모(선택) — 재생 시 화면에 함께 띄운다
    message     VARCHAR(100),
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    -- NULL = 아직 안 들음. 값이 있으면 소비 완료
    played_at   TIMESTAMP
);

-- 세션 시작 때마다 "내게 온 안 들은 부스터 하나"를 찾는 조회가 이 축을 탄다.
CREATE INDEX idx_workout_boosters_pending ON workout_boosters (receiver_id, played_at, id);
