-- 커플 콘텐츠(영화·공연·드라마/OTT) — Place(맛집 지도)와 별개 도메인(2026-08-24 결정).
-- 좌표·주소·카테고리가 없는 게 정상인 항목을 places 에 섞지 않기 위해 분리했다.
-- 럽슐랭 등급 산정 규칙은 lovelichelin_ratings(V54)의 place_ratings/lovelichelin_tier 와 동일하게
-- 그대로 미러링한다 — ContentService.computeTier 참고.
CREATE TABLE contents (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id  BIGINT       NOT NULL REFERENCES relations (id),
    title      VARCHAR(100) NOT NULL,
    type       VARCHAR(20)  NOT NULL,                    -- MOVIE / PERFORMANCE / DRAMA
    status     VARCHAR(20)  NOT NULL DEFAULT 'WISHLIST',  -- WISHLIST / DONE
    added_by   BIGINT       NOT NULL REFERENCES users (id),
    lovelichelin_tier INTEGER NOT NULL DEFAULT 0,
    lovelichelin_certified_at TIMESTAMP,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE content_logs (
    id         BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT   NOT NULL REFERENCES contents (id) ON DELETE CASCADE,
    logged_by  BIGINT   NOT NULL REFERENCES users (id),
    watched_at DATE     NOT NULL DEFAULT CURRENT_DATE,
    -- INTEGER (SMALLINT 아님) — JPA 엔티티(ContentLog.rating: Integer)와 맞춘다.
    -- place_visits 가 V8 에서 SMALLINT 로 만들었다가 ddl-auto=validate 부팅을 막아
    -- V11 에서 고친 전례가 있어(찾은 int2, 기대한 integer) 처음부터 INTEGER 로 만든다.
    rating     INTEGER CHECK (rating BETWEEN 1 AND 5),
    memo       TEXT,
    image_url  VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE content_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL REFERENCES contents (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    revisit_intent BOOLEAN,
    rated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (content_id, user_id)
);

CREATE INDEX idx_contents_couple ON contents (couple_id);
CREATE INDEX idx_content_logs_content ON content_logs (content_id);
CREATE INDEX idx_content_ratings_content ON content_ratings (content_id);
