-- 중요 대화 북마크 — docs/CHAT_RETENTION_AND_KAKAO_BENCHMARK_2026-09-03.md §3
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)

-- 커플 공용으로 본다: 한쪽이 저장하면 둘 다 목록에서 본다(saved_by 는 표시용).
-- 같은 메시지를 중복 저장하지 않게 UNIQUE(message_id) — "저장했나/안 했나"만 있고
-- "누가 몇 번 저장했나"는 없다(§3-2 설계 그대로).
CREATE TABLE chat_message_bookmarks (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT    NOT NULL REFERENCES relations (id) ON DELETE CASCADE,
    message_id  BIGINT    NOT NULL REFERENCES chat_messages (id) ON DELETE CASCADE,
    saved_by    BIGINT    NOT NULL REFERENCES users (id),
    memo        VARCHAR(200),
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (message_id)
);
CREATE INDEX idx_chat_message_bookmarks_relation ON chat_message_bookmarks (relation_id, id);
