-- 예약 전송 — docs/CHAT_RETENTION_AND_KAKAO_BENCHMARK_2026-09-03.md §6 5순위
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)

-- sender_id 가 관계를 벗어나 메시지를 예약해두는 걸 막는 검증은 서비스 계층 책임이다
-- (다른 테이블들과 같은 패턴 — chat_messages 도 FK 로 방을 제한하지 않는다).
-- sent_message_id 는 실제 발송된 chat_messages 행을 가리키는 정보용 참조라 ON DELETE SET NULL —
-- 원본 메시지가 지워져도(탈퇴 등) 예약 이력 자체는 남겨둔다.
CREATE TABLE scheduled_chat_messages (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id     BIGINT      NOT NULL REFERENCES relations (id) ON DELETE CASCADE,
    sender_id       BIGINT      NOT NULL REFERENCES users (id),
    message_type    VARCHAR(20) NOT NULL,
    content         TEXT,
    image_url       VARCHAR(500),
    scheduled_at    TIMESTAMP   NOT NULL,
    sent_at         TIMESTAMP,
    sent_message_id BIGINT      REFERENCES chat_messages (id) ON DELETE SET NULL,
    canceled_at     TIMESTAMP,
    created_at      TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- 스위퍼가 5초마다 훑는 조회(발송 대상: sent_at·canceled_at 둘 다 NULL, scheduled_at 지남)와
-- 방별 대기 목록 조회(relation_id) 양쪽에 쓰인다.
CREATE INDEX idx_scheduled_chat_messages_due
    ON scheduled_chat_messages (sent_at, canceled_at, scheduled_at);
CREATE INDEX idx_scheduled_chat_messages_relation
    ON scheduled_chat_messages (relation_id, scheduled_at);
