-- 공지 고정 — docs/CHAT_RETENTION_AND_KAKAO_BENCHMARK_2026-09-03.md §3, §6 5순위
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)

-- 관계당 하나만 고정된다("지금 필요한 것", 북마크와 달리 짧고 자주 바뀐다 — §3 표 참고).
-- UNIQUE(relation_id)로 DB 레벨에서도 "하나만" 을 강제한다(서비스 로직과 이중 방어).
-- 새 메시지로 교체할 땐 행을 지우지 않고 message_id/pinned_by/pinned_at 을 갱신한다.
CREATE TABLE chat_pinned_messages (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT    NOT NULL REFERENCES relations (id) ON DELETE CASCADE,
    message_id  BIGINT    NOT NULL REFERENCES chat_messages (id) ON DELETE CASCADE,
    pinned_by   BIGINT    NOT NULL REFERENCES users (id),
    pinned_at   TIMESTAMP NOT NULL,
    UNIQUE (relation_id)
);
