-- 끼니 알림 — 사용자가 등록한 아침/점심/저녁 시간에 "오늘 기록했나요?" 를 묻는 리마인드
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)

-- 한 사람당 끼니 타입(BREAKFAST/LUNCH/DINNER)마다 최대 한 행 — 시간을 바꾸면 UPDATE,
-- 끄면 DELETE. 별도 enabled 컬럼을 두지 않는다: 행이 없으면 그 끼니는 꺼진 것이다.
CREATE TABLE meal_reminders (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (id),
    meal_type     VARCHAR(20) NOT NULL,
    reminder_time TIME        NOT NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_meal_reminders_user_type UNIQUE (user_id, meal_type)
);

-- 매분 도는 스케줄러가 "지금 이 분(minute)에 울려야 하는 행" 을 훑는 조회
CREATE INDEX idx_meal_reminders_time ON meal_reminders (reminder_time);
