-- 일상 포스트 여러 장 사진 (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)
--
-- feed_posts.image_url(대표/첫 사진)은 건드리지 않는다 — 기존 글·기존 쿼리
-- (FeedPostRepository.findPhotos/findAlbumCandidates, TripAlbumService 등)가 전부
-- 그 컬럼을 대표 사진으로 계속 쓴다. 여기는 "전체 목록"만 추가로 담는 테이블이라
-- 새 글은 photos[0]과 image_url이 항상 같은 값을 갖는다(중복 저장, 의도한 것).
CREATE TABLE feed_post_photos (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id  BIGINT       NOT NULL REFERENCES feed_posts (id) ON DELETE CASCADE,
    url      VARCHAR(500) NOT NULL,
    order_no INT          NOT NULL DEFAULT 0
);

-- 타임라인이 포스트 여러 건의 사진을 한 번에 배치 조회하는 조회 패턴
CREATE INDEX idx_feed_post_photos_post ON feed_post_photos (post_id, order_no);
