-- 우리 이모지 — 상대(또는 내) 사진 한 장으로 AI 가 그린 감정별 캐릭터 이모지. 커플 소유.
-- 한 번의 생성(batch_id)이 감정별로 여러 행(기본 6)을 남긴다. 세트 테이블은 따로 두지 않는다 —
-- 테이블이 하나 늘 때마다 Purger 순서가 늘어난다(docs/COUPLE_EMOJI_AI_DESIGN_2026-09-08.md §5-4).
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)

CREATE TABLE couple_emojis (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id     BIGINT       NOT NULL REFERENCES relations (id),
    created_by      BIGINT       NOT NULL REFERENCES users (id),
    subject_user_id BIGINT       NOT NULL REFERENCES users (id),   -- 누구 얼굴인가
    batch_id        VARCHAR(36)  NOT NULL,                         -- 같은 생성에서 나온 묶음
    emotion         VARCHAR(20)  NOT NULL,                         -- ANGRY/HAPPY/EXCITED/SAD/SLEEPY/LOVE
    image_url       VARCHAR(500) NOT NULL,
    prompt_version  VARCHAR(20)  NOT NULL,                         -- 그림체를 바꿔도 옛 세트의 출처를 알 수 있게
    identity_facts  VARCHAR(500),                                  -- 텍스트 모델이 뽑은 외형 사실(2단계 생성, §12-3)
    deleted_at      TIMESTAMP,                                     -- 트레이에서만 숨김. 지난 메시지는 계속 보인다(§5-6)
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 트레이 조회: 관계의 살아 있는 이모지를 최신순으로
CREATE INDEX idx_couple_emojis_relation ON couple_emojis (relation_id, deleted_at);
