-- 협동 스도쿠 (2026-09-09) — docs/COUPLE_GAMES_DESIGN_2026-09-09.md 3절
--
-- 커플이 같은 판을 둘이 자유롭게 채우는 게임. 판 하나를 81자 문자열로 든다 —
-- 칸 테이블·수 이력 테이블을 두지 않는 이유는 "누가 몇 칸"이 owner_map 으로 충분하고,
-- 테이블이 하나면 Purger 도 한 줄이기 때문이다. game_type 을 두어 오목·직소가 같은 테이블을 쓴다.
--
-- owner_map 의 '1'/'2' 는 relations.user_a_id/user_b_id 가 아니라 created_by 기준이다.
-- Relation.transferOwnership 이 A/B 를 바꿀 수 있어 A/B 에 매달면 색이 뒤집힌다.
CREATE TABLE couple_games (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id    BIGINT       NOT NULL REFERENCES relations (id),
    game_type    VARCHAR(20)  NOT NULL,
    difficulty   VARCHAR(10)  NOT NULL,
    puzzle       VARCHAR(81)  NOT NULL,
    solution     VARCHAR(81)  NOT NULL,
    board        VARCHAR(81)  NOT NULL,
    owner_map    VARCHAR(81)  NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    created_by   BIGINT       NOT NULL REFERENCES users (id),
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMP
);

CREATE INDEX idx_couple_games_couple_status ON couple_games (couple_id, status, created_at DESC);
