-- 커플 맛집 지도 (PLAN.md: Place Map) — 장소 핀 + 방문 기록
-- lat/lng 는 지도 SDK(좌표 선택 UI) 도입 전까지 NULL 허용
CREATE TABLE places (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id  BIGINT        NOT NULL REFERENCES relations (id),
    name       VARCHAR(100)  NOT NULL,
    address    TEXT,
    lat        DECIMAL(10, 7),
    lng        DECIMAL(10, 7),
    category   VARCHAR(30),
    status     VARCHAR(20)   NOT NULL DEFAULT 'WISHLIST',   -- VISITED / WISHLIST
    added_by   BIGINT        NOT NULL REFERENCES users (id),
    created_at TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE TABLE place_visits (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id   BIGINT   NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    visited_by BIGINT   NOT NULL REFERENCES users (id),
    visited_at DATE     NOT NULL DEFAULT CURRENT_DATE,
    rating     SMALLINT CHECK (rating BETWEEN 1 AND 5),
    memo       TEXT,
    image_url  VARCHAR(500),
    meal_id    BIGINT REFERENCES meals (id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_places_couple ON places (couple_id);
CREATE INDEX idx_places_location ON places (lat, lng);
CREATE INDEX idx_place_visits_place ON place_visits (place_id);
