-- Gemini 호출 한 건의 토큰 사용량 — "AI 원가가 어디서 나가는가"를 추측이 아니라 숫자로 본다.
--
-- 이게 없어서 생긴 문제: Micrometer(fitto.ai.gemini.call)는 호출의 <소요 시간과 결과>만 남기고
-- <얼마나 썼는지>는 남기지 않았다. 그래서 청구서를 받아도 어느 기능이 얼마를 썼는지 역산할
-- 방법이 없었고, 단가 논의가 전부 가정 위에서 돌았다.
--
-- 여기서 뽑을 두 가지:
--   · 기능별 원가 비중      = feature_code 로 묶어 토큰 합
--   · 유저별 월 원가 상위 N = (user_id, created_at) 로 묶어 토큰 합
-- 개인 개발 앱의 적자는 평균이 아니라 헤비 유저 몇 명이 만든다 — 두 번째가 그걸 보는 자리다.
--
-- user_id 에 FK 를 걸지 않는다. 이 행은 AiJobService 의 백그라운드 스레드가 쓰는데, 사용자가
-- 그 사이 탈퇴하면 FK 위반으로 기록이 실패한다 — 계측 때문에 AI 기능이 흔들리면 본말전도다.
-- 대신 UserDataPurger 가 탈퇴 시 명시적으로 거둔다(feed_reactions 와 같은 방식).
--
-- (H2 호환 구문만 사용 — 테스트가 동일 마이그레이션을 적용한다)

CREATE TABLE ai_usage_logs (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL,                    -- FK 없음(위 주석)
    feature_code     VARCHAR(40) NOT NULL,                    -- Feature enum 이름
    model            VARCHAR(60) NOT NULL,                    -- 1차/폴백/이미지 모델이 여기서 갈린다
    prompt_tokens    INTEGER     NOT NULL DEFAULT 0,
    candidates_tokens INTEGER    NOT NULL DEFAULT 0,          -- 이미지 생성은 이 값이 곧 장당 원가다
    thoughts_tokens  INTEGER     NOT NULL DEFAULT 0,          -- output 단가로 과금되는 thinking 토큰
    cached_tokens    INTEGER     NOT NULL DEFAULT 0,
    total_tokens     INTEGER     NOT NULL DEFAULT 0,
    image_count      INTEGER     NOT NULL DEFAULT 0,          -- 이번 호출에 <보낸> 이미지 파트 수
    attempt          INTEGER     NOT NULL DEFAULT 1,          -- 1 이 아니면 재시도 끝에 성공한 것
    created_at       TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- 유저별 월 원가 상위 N
CREATE INDEX idx_ai_usage_logs_user ON ai_usage_logs (user_id, created_at);
-- 기간별 전체 집계 / 오래된 행 정리
CREATE INDEX idx_ai_usage_logs_created ON ai_usage_logs (created_at);
