-- 스티커 팩 + 낱개 구매 (2026-09-21)
--
-- <b>왜 팩이라는 개념을 다시 만드는가</b>: 2026-09-14 에 `StickerPack` enum 을 지웠다
-- (docs/STICKER_PACK_OVERLAP_2026-09-14.md). 그때 지운 것은 <b>유니코드 이모지를 팩으로
-- 묶어 PRO 로 팔던 것</b>이고, 근거는 "폰 키보드에 이미 있는 글자를 파는 모양"이었다.
-- 여기서 되살리는 팩은 그것과 다르다 — 묶는 대상이 Lottie 애니메이션과 번들 PNG 라
-- 키보드로 대체할 수 없고, 무엇보다 <b>판정 기준이 아니라 상품 단위</b>다.
--
-- 지금까지의 판정은 "이 코드가 premium 인가"(enum 의 boolean 한 칸)였다. 그래서 PRO 냐
-- 아니냐밖에 답할 수 없었다. 낱개 구매가 붙으면 답이 셋으로 갈린다 —
--   (1) 전부 무료          : is_pro_only = false AND price = 0
--   (2) PRO 면 전부        : 구독이 있으면 유료 팩 전체가 열린다
--   (3) 이 팩만 샀다       : user_sticker_purchases 에 (user_id, pack_id) 가 있다
-- (2) 와 (3) 을 동시에 답하려면 "팩"이 행으로 존재해야 한다. enum 의 boolean 으로는
-- 무엇을 샀는지를 적을 자리가 없다.
--
-- <b>가격은 여기 있고 스토어에도 있다.</b> 이 값은 표시·정렬용이고 실제 과금은 스토어가
-- 한다(상품 id 는 코드에서 'sticker_pack_' + lower(id) 로 만든다 — StickerPack.productId).
-- 두 값이 어긋나면 스토어가 이긴다.
--
-- H2/PostgreSQL 양립: JSONB·ON CONFLICT·SERIAL 을 쓰지 않는다(CLAUDE.md 4절).
-- IDENTITY 는 V90(ai_usage_logs)과 같은 구문을 쓴다.

CREATE TABLE sticker_packs (
    id          VARCHAR(40)  PRIMARY KEY,               -- 코드에서 상수로 참조한다(StickerPackIds)
    title       VARCHAR(60)  NOT NULL,                  -- 패널 스트립·구매 시트에 그대로 뜨는 한국어 이름
    category    VARCHAR(20)  NOT NULL,                  -- ANIMATED · IMAGE · MOOD · TOUCH
    is_pro_only BOOLEAN      NOT NULL DEFAULT FALSE,
    price       INTEGER      NOT NULL DEFAULT 0,        -- 낱개 구매가(KRW). 0 이면 낱개로 팔지 않는다
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 낱개 구매 기록 — "이 사람은 이 팩을 샀다". 구독과 독립이라 구독이 끊겨도 남는다.
--
-- user_id 에 FK 를 걸지 않는다: 이 행은 스토어 웹훅/검증 경로에서도 쓰이고, 무엇보다
-- 탈퇴 시 FK 위반으로 탈퇴 전체가 실패하는 경로를 늘리지 않기 위해서다(V90 과 같은 판단).
-- 대신 UserDataPurger 가 탈퇴 시 명시적으로 거둔다 — FK 가 없으니 빠뜨리면 조용히 남는다.
CREATE TABLE user_sticker_purchases (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL,
    sticker_pack_id VARCHAR(40) NOT NULL REFERENCES sticker_packs(id),
    -- 스토어 거래 id(Play purchaseToken / App Store transactionId). 재검증·환불 대조에 쓴다.
    -- 스토어 등록 전 수동 지급 경로를 남겨 두려고 NULL 을 허용한다.
    transaction_id  VARCHAR(255),
    purchased_at    TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- 같은 팩을 두 번 사도 한 번만 남는다 — 검증 재호출(앱 재설치·복원)이 행을 늘리면
-- "몇 개 샀나"가 아니라 "샀나"를 묻는 판정이 흔들린다.
CREATE UNIQUE INDEX uq_user_sticker_purchase ON user_sticker_purchases (user_id, sticker_pack_id);
-- 스티커 한 장 보낼 때마다 도는 질의 — 위 unique 인덱스의 선행 컬럼이 user_id 라 그대로 탄다.

-- ── 시드 ────────────────────────────────────────────────────────────────────
--
-- <b>무료 팩은 지금 무료인 것을 그대로 옮긴 것이다.</b> 새로 잠그는 코드는 하나도 없다 —
-- 2026-09-14 의 교훈("무료라고 보여 준 것을 서버가 막는다")을 반복하지 않는다.
-- 유료 팩 5개는 기존 AnimatedSticker.premium = true 24종을 <b>주제별로 쪼갠 것</b>이고,
-- PRO 사용자에게는 전과 똑같이 24종 전부가 열린다. 달라지는 건 무료 사용자가 이제
-- "전부 아니면 전무" 대신 원하는 한 팩만 살 수 있다는 것뿐이다.
--
-- <b>이미지 스티커(IMAGE)는 한 팩도 시드하지 않는다.</b> 2026-09-21 에 그림 출처를 정리하며
-- 곰돌이 10 · 더비 14 · 블리 14 를 전부 피커에서 내렸다. 팩에 없는 코드는 무료로 통과하므로
-- 지난 말풍선은 그대로 그려진다 — MoodPack 의 "목록에 없는 이모지는 무료다"와 같은 규칙이다.
-- 되살리거나 새 캐릭터를 붙일 때 IMAGE 카테고리 행을 여기에 더하면 된다.

INSERT INTO sticker_packs (id, title, category, is_pro_only, price) VALUES
    ('ANIM_BASIC',     '움직이는 이모티콘', 'ANIMATED', FALSE, 0),
    ('MOOD_BASIC',     '기본 무드',         'MOOD',     FALSE, 0),
    ('TOUCH_BASIC',    '기본 터치',         'TOUCH',    FALSE, 0),
    ('ANIM_LOVE',      '두근두근',          'ANIMATED', TRUE,  1200),
    ('ANIM_UPSET',     '속상해',            'ANIMATED', TRUE,  1200),
    ('ANIM_CHILL',     '여유롭게',          'ANIMATED', TRUE,  1200),
    ('ANIM_CELEBRATE', '축하해',            'ANIMATED', TRUE,  1200),
    ('ANIM_CHEER',     '응원해',            'ANIMATED', TRUE,  1200),
    ('MOOD_PREMIUM',   '확장 무드',         'MOOD',     TRUE,  1200),
    ('TOUCH_PREMIUM',  '프리미엄 터치',      'TOUCH',    TRUE,  1200);
