-- 커플 일상 피드 (PLAN.md: Couple Feed) — 일상 포스트 + 이모지 반응
-- 타임라인의 운동/식단/맛집 방문은 원본 테이블에서 집계하므로 복제 테이블 없음
CREATE TABLE feed_posts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id  BIGINT    NOT NULL REFERENCES relations (id),
    author_id  BIGINT    NOT NULL REFERENCES users (id),
    content    TEXT,                 -- 글/사진 중 하나는 필수 (서비스 검증)
    image_url  VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE feed_reactions (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT      NOT NULL REFERENCES feed_posts (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    emoji      VARCHAR(10) NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    UNIQUE (post_id, user_id, emoji)
);

CREATE INDEX idx_feed_posts_couple ON feed_posts (couple_id, created_at DESC);
CREATE INDEX idx_feed_reactions_post ON feed_reactions (post_id);
