/**
 * 스티커 팩 — 판매 단위. 백엔드 `com.fitto.chat.domain.StickerPacks` 와 id 가 짝을 맞춘다.
 *
 * <p><b>이 파일은 2026-09-14 에 지웠던 stickerPacks.ts 와 다른 물건이다.</b> 그때 지운 것은
 * 유니코드 이모지를 팩으로 묶어 PRO 로 팔던 것이고, 근거는 "폰 키보드에 이미 있는 글자를
 * 파는 모양"이었다(docs/STICKER_PACK_OVERLAP_2026-09-14.md). 여기서 묶는 건 Lottie
 * 애니메이션과 번들 PNG 라 키보드로 대체할 수 없고, 무엇보다 <b>판정 기준이 아니라 상품
 * 단위</b>다 — 잠금 여부는 서버가 팩 단위로 내려주고(`api/stickers.ts`) 이 파일은
 * "어느 그림이 어느 팩인가"만 안다.
 *
 * <p><b>여기에 없는 코드는 무료다.</b> 서버도 같은 규칙이라(StickerPacks 주석) 양쪽이
 * 저절로 맞는다. 유니코드 이모지, 우리 이모지, 그리고 피커에서 내린 더비·블리가 전부
 * 이 경로로 지난다 — 그때의 사고("무료라고 보여 준 것을 서버가 막는다")를 구조로 막는 자리다.
 */

/**
 * 무료 팩 — 누구나 쓴다. 움직이는 이모티콘은 이제 전부 여기 있고, <b>4팩이다</b>.
 *
 * <p>2026-09-22 에 8팩에서 합쳤다(V100). 110종을 8칸으로 쪼개니 한 팩이 7~18장이라 고르는
 * 것보다 팩을 넘기는 데 손이 더 갔다. 같은 날 격자를 7칸으로 줄여 한 번에 28장이 보인다.
 */
export const PACK_ANIM_LOVE = 'ANIM_LOVE';
/** 웃음·축하 (옛 ANIM_CELEBRATE 흡수) */
export const PACK_ANIM_FUN = 'ANIM_FUN';
/** 위로·응원 (옛 ANIM_UPSET 흡수) */
export const PACK_ANIM_CHEER = 'ANIM_CHEER';
/** 일상 — 동물·먹을 것·날씨 */
export const PACK_ANIM_DAILY = 'ANIM_DAILY';
export const PACK_MOOD_BASIC = 'MOOD_BASIC';
export const PACK_TOUCH_BASIC = 'TOUCH_BASIC';
/** 캐릭터 스티커 — 상점 상품이지만 첫 두 팩은 0원이다 */
export const PACK_EGG_BOILED = 'EGG_BOILED';
export const PACK_EGG_DUO = 'EGG_DUO';

/** 유료 팩 — PRO 구독이면 전부, 아니면 낱개로 산 것만 */
export const PACK_MOOD_PREMIUM = 'MOOD_PREMIUM';
export const PACK_TOUCH_PREMIUM = 'TOUCH_PREMIUM';

/**
 * 움직이는 이모티콘 코드 → 팩. 8팩 전부 무료다.
 *
 * <p>`animatedStickers.ts` 의 `packId` 와 <b>어긋나면 안 된다</b>. `npm run typecheck` 는
 * 이걸 잡지 못하므로 백엔드 `StickerPackSyncTest` 가 대신 본다. 두 파일 모두
 * `gen_catalog.py` 의 한 원본에서 생성했다.
 */
export const ANIMATED_STICKER_PACKS: Record<string, string> = {
  // ── 사랑 (ANIM_LOVE) ──
  ANIM_TWO_HEARTS: PACK_ANIM_LOVE,
  ANIM_KISS: PACK_ANIM_LOVE,
  ANIM_LOVE_FACE: PACK_ANIM_LOVE,
  ANIM_HEART: PACK_ANIM_LOVE,
  ANIM_SPARKLING_HEART: PACK_ANIM_LOVE,
  ANIM_HEART_EYES: PACK_ANIM_LOVE,
  ANIM_STAR_STRUCK: PACK_ANIM_LOVE,
  ANIM_HUG: PACK_ANIM_LOVE,
  ANIM_FINGER_HEART: PACK_ANIM_LOVE,
  ANIM_HAND_HEART: PACK_ANIM_LOVE,
  ANIM_CUPID: PACK_ANIM_LOVE,
  ANIM_GIFT_HEART: PACK_ANIM_LOVE,
  ANIM_GROWING_HEART: PACK_ANIM_LOVE,
  ANIM_BEATING_HEART: PACK_ANIM_LOVE,
  ANIM_REVOLVING_HEARTS: PACK_ANIM_LOVE,
  ANIM_LIPS: PACK_ANIM_LOVE,
  ANIM_HEART_CAT: PACK_ANIM_LOVE,
  ANIM_LOVE_LETTER: PACK_ANIM_LOVE,
  // ── 웃음·축하 ① 웃음·장난 (ANIM_FUN) ──
  ANIM_JOY: PACK_ANIM_FUN,
  ANIM_ZANY: PACK_ANIM_FUN,
  ANIM_COOL: PACK_ANIM_FUN,
  ANIM_SMILE: PACK_ANIM_FUN,
  ANIM_YAWN: PACK_ANIM_FUN,
  ANIM_SLEEPING: PACK_ANIM_FUN,
  ANIM_OOPS: PACK_ANIM_FUN,
  ANIM_FLUSHED: PACK_ANIM_FUN,
  ANIM_RELIEVED: PACK_ANIM_FUN,
  ANIM_DROOL: PACK_ANIM_FUN,
  ANIM_WOOZY: PACK_ANIM_FUN,
  ANIM_SMIRK: PACK_ANIM_FUN,
  ANIM_UPSIDE_DOWN: PACK_ANIM_FUN,
  ANIM_HALO: PACK_ANIM_FUN,
  ANIM_THINKING: PACK_ANIM_FUN,
  ANIM_MELTING: PACK_ANIM_FUN,
  ANIM_SALUTE: PACK_ANIM_FUN,
  ANIM_SHUSH: PACK_ANIM_FUN,
  // ── 위로·응원 ① 속상해 (ANIM_CHEER) ──
  ANIM_SOB: PACK_ANIM_CHEER,
  ANIM_HOLDING_TEARS: PACK_ANIM_CHEER,
  ANIM_RAGE: PACK_ANIM_CHEER,
  ANIM_HUFF: PACK_ANIM_CHEER,
  ANIM_CRY: PACK_ANIM_CHEER,
  ANIM_DISAPPOINTED: PACK_ANIM_CHEER,
  ANIM_PENSIVE: PACK_ANIM_CHEER,
  ANIM_WEARY: PACK_ANIM_CHEER,
  ANIM_TIRED: PACK_ANIM_CHEER,
  ANIM_ANGRY: PACK_ANIM_CHEER,
  ANIM_CURSING: PACK_ANIM_CHEER,
  ANIM_UNAMUSED: PACK_ANIM_CHEER,
  ANIM_EYE_ROLL: PACK_ANIM_CHEER,
  ANIM_BROKEN_HEART: PACK_ANIM_CHEER,
  ANIM_ANXIOUS: PACK_ANIM_CHEER,
  ANIM_SWEAT: PACK_ANIM_CHEER,
  // ── 웃음·축하 ② 축하해 (ANIM_FUN) ──
  ANIM_PARTY_FACE: PACK_ANIM_FUN,
  ANIM_PARTY_POPPER: PACK_ANIM_FUN,
  ANIM_BIRTHDAY_CAKE: PACK_ANIM_FUN,
  ANIM_GIFT: PACK_ANIM_FUN,
  ANIM_ROSE: PACK_ANIM_FUN,
  ANIM_BOUQUET: PACK_ANIM_FUN,
  ANIM_CONFETTI: PACK_ANIM_FUN,
  ANIM_BALLOON: PACK_ANIM_FUN,
  ANIM_SPARKLES: PACK_ANIM_FUN,
  ANIM_CHEERS: PACK_ANIM_FUN,
  ANIM_CHAMPAGNE: PACK_ANIM_FUN,
  ANIM_TROPHY: PACK_ANIM_FUN,
  ANIM_RING: PACK_ANIM_FUN,
  ANIM_CHERRY_BLOSSOM: PACK_ANIM_FUN,
  // ── 위로·응원 ② 응원해 (ANIM_CHEER) ──
  ANIM_THUMBS_UP: PACK_ANIM_CHEER,
  ANIM_PLEADING: PACK_ANIM_CHEER,
  ANIM_FIRE: PACK_ANIM_CHEER,
  ANIM_MUSCLE: PACK_ANIM_CHEER,
  ANIM_PRAY: PACK_ANIM_CHEER,
  ANIM_EYES: PACK_ANIM_CHEER,
  ANIM_CLAP: PACK_ANIM_CHEER,
  ANIM_RAISED_HANDS: PACK_ANIM_CHEER,
  ANIM_FIST: PACK_ANIM_CHEER,
  ANIM_HUNDRED: PACK_ANIM_CHEER,
  ANIM_STAR: PACK_ANIM_CHEER,
  ANIM_GLOWING_STAR: PACK_ANIM_CHEER,
  ANIM_POINTING: PACK_ANIM_CHEER,
  ANIM_HANDSHAKE: PACK_ANIM_CHEER,
  ANIM_TARGET: PACK_ANIM_CHEER,
  ANIM_ZAP: PACK_ANIM_CHEER,
  ANIM_WAVE: PACK_ANIM_CHEER,
  ANIM_LOVE_SIGN: PACK_ANIM_CHEER,
  // ── 일상 ① 동물 (ANIM_DAILY) ──
  ANIM_CAT: PACK_ANIM_DAILY,
  ANIM_BEAR: PACK_ANIM_DAILY,
  ANIM_PANDA: PACK_ANIM_DAILY,
  ANIM_FOX: PACK_ANIM_DAILY,
  ANIM_LION: PACK_ANIM_DAILY,
  ANIM_FROG: PACK_ANIM_DAILY,
  ANIM_PENGUIN: PACK_ANIM_DAILY,
  ANIM_CHICK: PACK_ANIM_DAILY,
  ANIM_UNICORN: PACK_ANIM_DAILY,
  // ── 일상 ② 먹을 것 (ANIM_DAILY) ──
  ANIM_PIZZA: PACK_ANIM_DAILY,
  ANIM_COFFEE: PACK_ANIM_DAILY,
  ANIM_RAMEN: PACK_ANIM_DAILY,
  ANIM_BURGER: PACK_ANIM_DAILY,
  ANIM_ICE_CREAM: PACK_ANIM_DAILY,
  ANIM_STRAWBERRY: PACK_ANIM_DAILY,
  ANIM_WATERMELON: PACK_ANIM_DAILY,
  ANIM_AVOCADO: PACK_ANIM_DAILY,
  ANIM_EGG: PACK_ANIM_DAILY,
  ANIM_BUBBLE_TEA: PACK_ANIM_DAILY,
  // ── 일상 ③ 날씨 (ANIM_DAILY) ──
  ANIM_RAIN: PACK_ANIM_DAILY,
  ANIM_SNOWMAN: PACK_ANIM_DAILY,
  ANIM_RAINBOW: PACK_ANIM_DAILY,
  ANIM_SNOWFLAKE: PACK_ANIM_DAILY,
  ANIM_OCEAN: PACK_ANIM_DAILY,
  ANIM_MAPLE: PACK_ANIM_DAILY,
  ANIM_SUN: PACK_ANIM_DAILY,
};

/**
 * 이미지 스티커 캐릭터 키 → 팩. 캐릭터 한 마리가 곧 한 팩이다.
 *
 * <p>캐릭터를 더 붙이면 여기에 한 줄, 그리고 마이그레이션 시드에 한 줄이면 끝이다.
 * 유료로 팔 캐릭터는 `is_pro_only = TRUE` + 가격을 주면 잠금·구매 흐름이 저절로 붙는다.
 */
export const CHARACTER_PACKS: Record<string, string> = {
  boiled: PACK_EGG_BOILED,
  duo: PACK_EGG_DUO,
};

/** 이 스티커 코드가 속한 팩. 팩이 없으면 undefined(= 무료). */
export function packIdOfSticker(code: string): string | undefined {
  return ANIMATED_STICKER_PACKS[code];
}
